json.id build.id
json.build_name build.build_name
json.character_name build.character_name
json.character_class build.character_class
json.user_id build.user_id
json.gloves_rune build.gloves_rune
json.chest_rune build.chest_rune
json.legs_rune build.legs_rune
json.created_at build.created_at
json.updated_at build.updated_at
