json.id build.id
json.build_name build.build_name
json.character_name build.character_name
json.character_class build.character_class
json.user_id build.user_id
json.gloves_rune_id build.gloves_rune_id
json.chest_rune_id build.chest_rune_id
json.legs_rune_id build.legs_rune_id
json.created_at build.created_at
json.updated_at build.updated_at
