# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Druid Chest Runes
# Rune.create!(name: "Living Seed", character_class: "Druid", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_detectinvisibility.jpg", description: "When you critically heal your target with any healing spell you plant a Living Seed on the target for 30% of the amount healed. The Living Seed will bloom when the target is next attacked. Lasts 15 sec.", instructions: nil)
# Rune.create!(name: "Fury of Stormrage", character_class: "Druid", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_staff_90.jpg", description: "Reduces the mana cost of Wrath by 100% and each time you deal damage with Wrath you have a 12% chance for your next cast of Healing Touch within 15 sec to be instant.", instructions: nil)
# Rune.create!(name: "Survival of the Fittest", character_class: "Druid", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_enrage.jpg", description: "Reduces the chance you'll be critically hit by melee attacks by 6% and reduces all damage taken by 10%. Damage taken reduced by an additional 10% while in Bear Form or Dire Bear Form.", instructions: nil)
# Rune.create!(name: "Wild Strikes", character_class: "Druid", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_swipe.jpg", description: "While you are in Cat Form, Bear Form, or Dire Bear Form, party members within 20 yards gain increased combat ferocity.  Each melee hit has a 20% chance of granting the attacker an extra attack with 20% additional Attack Power. No effect if the party member is already benefitting from Windfury Totem.", instructions: nil)

# # Druid Gloves Runes
# Rune.create!(name: "Sunfire", character_class: "Druid", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_mage_firestarter.jpg", description: "Burns the enemy for 55 to 65 Nature damage and then an additional 110 Nature damage over 12 sec.", instructions: nil)
# Rune.create!(name: "Mangle", character_class: "Druid", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_mangle2.jpg", description: "Gain the Mangle (Bear) ability and replace your Claw ability with Mangle (Cat). This ability benefits from and triggers all effects associated with Claw and Maul.", instructions: nil)
# Rune.create!(name: "Lacerate", character_class: "Druid", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_lacerate.jpg", description: "Lacerates the enemy target, making them bleed for 42 damage over 15 sec plus 20% weapon damage per existing application of Lacerate on the target. Causes a high amount of threat. This effect stacks up to 5 times on the same target.", instructions: nil)
# Rune.create!(name: "Wild Growth", character_class: "Druid", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_flourish.jpg", description: "Heals all of target player's party members within 40 yards of target player for 156 over 7 sec. The amount healed is applied quickly at first, and slows down as Wild Growth reaches its full duration.", instructions: nil)

# # Druid Legs Runes
# Rune.create!(name: "Lifebloom", character_class: "Druid", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/inv_misc_herb_felblossom.jpg", description: "Heals the target for 45 over 7 sec.  When Lifebloom completes its duration or is dispelled, the target instantly heals for 91 and the Druid regains half the cost of the spell.  This effect can stack up to 3 times on the same target.", instructions: nil)
# Rune.create!(name: "Savage Roar", character_class: "Druid", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_druid_skinteeth.jpg", description: "Finishing move that increases physical damage done by 30% while in Cat Form.  Lasts longer per combo point:
#   1 point: 14 seconds
#   2 points: 19 seconds
#   3 points: 24 seconds
#   4 points: 29 seconds
#   5 points: 34 seconds", instructions: nil)
# Rune.create!(name: "Skull Bash", character_class: "Druid", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/inv_misc_bone_taurenskull_01.jpg", description: "Charge to a target within 13 yards and bash the target's skull, interrupting spellcasting and preventing any spell in that school from being cast for 2 sec. Shares a cooldown with Feral Charge.", instructions: nil)
# Rune.create!(name: "Starsurge", character_class: "Druid", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_arcane_arcane03.jpg", description: "Launch surging stellar energies that causes 57 to 70 Arcane damage. Starsurge benefits from and triggers most talents and effects that trigger or benefit from Wrath or Starfire.", instructions: nil)

# Hunter Gloves Runes
# Rune.create!(name: "Beast Mastery", character_class: "Hunter", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_physical_taunt.jpg", description: "Your pet's damage and health are increased by 30%, and its Focus regeneration by 80%. In addition, your pet's Growl now also Taunts the target to attack it for 3 sec.", instructions: nil)
# Rune.create!(name: "Carve", character_class: "Hunter", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_throwingknife_06.jpg", description: "A sweeping attack that strikes all enemies in front of you for 50% weapon damage.", instructions: nil)
# Rune.create!(name: "Chimera Shot", character_class: "Hunter", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_chimerashot2.jpg", description: "You deal 85% weapon damage, refreshing the current Sting on your target and triggering an effect: Serpent Sting - Instantly deals 40% of the damage done by your Serpent Sting. Viper Sting - Instantly restores mana to you equal to 60% of the total amount drained by your Viper Sting. Scorpid Sting - Attempts to Disarm the target for 10 sec. This effect cannot occur more than once per 1 minute.", instructions: nil)
# Rune.create!(name: "Explosive Shot", character_class: "Hunter", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_explosiveshot.jpg", description: "You fire an explosive charge into the enemy target, dealing 74-91 Fire damage to all enemies within 8 yards. The charge will deal damage again every second for an additional 2 sec. Cooldown shared with Arcane Shot.", instructions: nil)

# Hunter Chest Runes
# Rune.create!(name: "Heart of the Lion", character_class: "Hunter", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_pet_cat.jpg", description: "The hunter invokes the heart of a lion, increasing total stats by 10% for all nearby allies, and increasing total stats for the Hunter by an additional 10%.", instructions: nil)
# Rune.create!(name: "Cobra Strikes", character_class: "Hunter", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_cobrastrikes.jpg", description: "Your critical hits with Shot abilities cause your pet's next 2 special attacks to critically hit.", instructions: nil)
# Rune.create!(name: "Lone Wolf", character_class: "Hunter", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_mount_whitedirewolf.jpg", description: "You deal 15% increased damage with all attacks while you do not have an active pet.", instructions: nil)
# Rune.create!(name: "Master Marksman", character_class: "Hunter", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_mastermarksman.jpg", description: "Increases your critical strike chance by 5%, and reduces the Mana cost of all your Shot abilities by 25%.", instructions: nil)

# Hunter Legs Runes
# Rune.create!(name: "Flanking Strike", character_class: "Hunter", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_harass.jpg", description: "You and your pet deal simultaneous instant 100% melee damage. Afterward, your Mongoose Bite and Raptor Strike deal 10% increased damage for 10 sec, stacking up to 3 times. Raptor Strike has a 20% chance to reset the cooldown on Flanking Strike.", instructions: nil)
# Rune.create!(name: "Kill Command", character_class: "Hunter", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_killcommand.jpg", description: "Give the command to kill, increasing your pet's damage done from Claw and Bite by 60% for 30 sec.  Each Claw or Bite done by the pet reduces the damage bonus by 20%.", instructions: nil)
# Rune.create!(name: "Serpent Spread", character_class: "Hunter", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_serpentswiftness.jpg", description: "Targets hit by your Multi-Shot are also afflicted by your Serpent Sting for 6 sec.", instructions: nil)
# Rune.create!(name: "Sniper Training", character_class: "Hunter", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_snipershot.jpg", description: "Your Shot abilities gain 10% increased critical strike chance while you have not moved for the last 6 sec.", instructions: nil)

# Warrior Gloves Runes
# Rune.create!(name: "Devastate", character_class: "Warrior", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_sword_11.jpg", description: "While you are in Defensive Stance and have a shield equipped, Sunder Armor also deals 60% weapon damage, increased by 6% per application of Sunder Armor already on the target.", instructions: nil)
# Rune.create!(name: "Endless Rage", character_class: "Warrior", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warrior_innerrage.jpg", description: "You generate 25% more Rage from all damage you deal.", instructions: nil)
# Rune.create!(name: "Quick Strike", character_class: "Warrior", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_axe_03.jpg", description: "A reckless instant melee attack with your two-handed weapon dealing 50 to 83 physical damage. This ability benefits from and triggers all effects associated with Heroic Strike.", instructions: nil)
# Rune.create!(name: "Single-Minded Fury", character_class: "Warrior", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_relics_totemofrage.jpg", description: "While dual-wielding, your Physical damage and movement speed are increased by 10%.", instructions: nil)
# Rune.create!(name: "Victory Rush", character_class: "Warrior", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warrior_devastate.jpg", description: "Instantly attack the target causing 151 damage and healing you for 10% of your maximum health.  Only useable within 20 sec after you kill an enemy that yields experience or honor.", instructions: nil)

# Warrior Chest Runes
# Rune.create!(name: "Blood Frenzy", character_class: "Warrior", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_nature_bloodlust.jpg", description: "Each time you deal Bleed damage, you gain 3 Rage.", instructions: nil)
# Rune.create!(name: "Flagellation", character_class: "Warrior", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_mace_1h_stratholme_d_01.jpg", description: "Gain a 25% bonus to Physical damage done for 12 sec after activating Bloodrage or Berserker Rage.", instructions: nil)
# Rune.create!(name: "Raging Blow", character_class: "Warrior", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_hunter_swiftstrike.jpg", description: "A ferocious strike that deals 100% weapon damage, but can only be used while Enrage, Berserker Rage, or Bloodrage is active.", instructions: nil)
# Rune.create!(name: "Warbringer", character_class: "Warrior", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warrior_warbringer.jpg", description: "Your Charge, Intercept, and Intervene abilities are now usable while in combat and in any stance, and will all remove movement impairing effects when activated.", instructions: nil)

# Warrior Legs Runes
# Rune.create!(name: "Consumed by Rage", character_class: "Warrior", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_nature_shamanrage.jpg", description: "Enrages you and grants you a 20% melee damage bonus for 12 sec or up to a maximum of 12 swings after you exceed 80 Rage.", instructions: nil)
# Rune.create!(name: "Frenzied Assault", character_class: "Warrior", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warrior_unrelentingassault.jpg", description: "While wielding 2-handed weapons, your attack speed is increased by 20%.", instructions: nil)
# Rune.create!(name: "Furious Thunder", character_class: "Warrior", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_nature_lightning.jpg", description: "Thunder Clap now increases the time between attacks by an additional 6%, can be used in any stance, and deals 50% increased threat.", instructions: nil)

# Mage Gloves Runes
# Rune.create!(name: "Arcane Blast", character_class: "Mage", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_arcane_blast.jpg", description: "Blasts the target with energy, dealing 190 to 221 Arcane damage.  Each time you cast Arcane Blast, the damage and healing of all other Arcane spells is increased by 15% and mana cost of Arcane Blast is increased by 175%.  Effect stacks up to 4 times and lasts 6 sec or until any other Arcane damage or healing spell is cast.", instructions: nil)
# Rune.create!(name: "Ice Lance", character_class: "Mage", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_frost_frostblast.jpg", description: "Deals 23 to 27 Frost damage to an enemy target.  Causes triple damage against Frozen targets.", instructions: nil)
# Rune.create!(name: "Living Bomb", character_class: "Mage", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_mage_livingbomb.jpg", description: "The target becomes a Living Bomb, taking 142 Fire damage over 12 sec.  After 12 sec or when the spell is dispelled, the target explodes dealing 72 Fire damage to all enemies within 10 yards", instructions: nil)
# Rune.create!(name: "Rewind Time", character_class: "Mage", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_borrowedtime.jpg", description: "Your current target with your Temporal Beacon instantly heals all damage taken over the last 5 seconds. Ineffective on targets that did not have a Temporal Beacon 5 seconds ago.", instructions: nil)

# Mage Chest Runes
# Rune.create!(name: "Burnout", character_class: "Mage", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_mage_burnout.jpg", description: "Increases your spell critical strike chance with all spells by 15%, but your non-periodic spell critical strikes now have an additional mana cost of 1% of your base mana.", instructions: nil)
# Rune.create!(name: "Enlightenment", character_class: "Mage", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_arcane_mindmastery.jpg", description: "You deal 10% more damage while you have more than 70% mana. While below 30% mana 10% of your mana regeneration continues while casting.", instructions: nil)
# Rune.create!(name: "Fingers of Frost", character_class: "Mage", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_mage_wintersgrasp.jpg", description: "Gives your Chill effects a 15% chance to grant you the Fingers of Frost effect, which treats your next 2 spells cast as if the target were Frozen.  Lasts 15 sec.", instructions: nil)
# Rune.create!(name: "Regeneration", character_class: "Mage", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_enchant_essencenethersmall.jpg", description: "Heals the target for (* 42 / 100 * 3) health over 3 sec and applies Temporal Beacon for 30 sec. Temporal Beacon: Records the subject's space-time position. 80% of all Arcane damage done by the caster will be converted to chronomantic healing on each of the caster's current Temporal Beacon targets. This healing is reduced by 50% on self, and also reduced by 80% when damage is done by Arcane Explosion.
# ", instructions: nil)

# Mage Legs Runes
# Rune.create!(name: "Arcane Surge", character_class: "Mage", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_arcane_arcanetorrent.jpg", description: "Unleash all of your remaining mana in a surge of energy focused at the target dealing 95 to 111 Arcane damage, increased by up to 300% based on your mana remaining. Afterward, your normal mana regeneration is activated and increased by 300% for 8 sec.", instructions: nil)
# Rune.create!(name: "Icy Veins", character_class: "Mage", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_frost_coldhearted.jpg", description: "Hastens your spellcasting, increasing spell casting speed by 20% and reduces the pushback suffered from damaging attacks while casting by 100%. Lasts 20 sec.", instructions: nil)
# Rune.create!(name: "Living Flame", character_class: "Mage", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_fire_masterofelements.jpg", description: "Summons a spellfire flame that moves toward the target, leaving a trail of spellfire. This trail deals 42 Spellfire damage every second to nearby enemies. Lasts 20 sec.", instructions: nil)
# Rune.create!(name: "Mass Regeneration", character_class: "Mage", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/inv_enchant_essencenetherlarge.jpg", description: "Heals all of target player's party members within 30 yards of target player for 262 health over 3 sec and applies Temporal Beacon to each target for 15 sec. Temporal Beacon: Records the subject's space-time position. 80% of all Arcane damage done by the caster will be converted to chronomantic healing on each of the caster's current Temporal Beacon targets. This healing is reduced by 50% on self, and also reduced by 80% when damage is done by Arcane Explosion.", instructions: nil)

# Priest Gloves Runes
# Rune.create!(name: "Circle of Healing", character_class: "Priest", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_circleofrenewal.jpg", description: "Heals all of target player's party members within 40 yards of target player for 82 to 92.", instructions: nil)
# Rune.create!(name: "Mind Sear", character_class: "Priest", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_mindshear.jpg", description: "Causes an explosion of shadow magic around the enemy target, causing 35 to 39 Shadow damage every 1 sec for 5 sec to all enemies within 10 yards around the target.", instructions: nil)
# Rune.create!(name: "Penance", character_class: "Priest", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_penance.jpg", description: "Launches a volley of holy light at the target, causing 64 Holy damage to an enemy, or 171 healing to an ally, instantly and every 1 sec for 2 sec.", instructions: nil)
# Rune.create!(name: "Shadow Word: Death", character_class: "Priest", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_demonicfortitude.jpg", description: "A word of dark binding that inflicts 130 to 152 Shadow damage to the target.  If the target is not killed by Shadow Word: Death, the caster takes damage equal to the damage inflicted upon the target.", instructions: nil)

# Priest Chest Runes
# Rune.create!(name: "Serendipity", character_class: "Priest", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_serendipity.jpg", description: "Healing with Flash Heal reduces the cast time of your next Lesser Heal, Heal, Greater Heal, or Prayer of Healing by 20% for 20 sec, stacking up to 3 times.", instructions: nil)
# Rune.create!(name: "Strength of Soul", character_class: "Priest", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_greaterblessingofsanctuary.jpg", description: "Lesser Heal, Heal, Greater Heal, and Flash Heal reduce the remaining duration of Weakened Soul on targets they heal by 4 sec. In addition, targets of your Power Word: Shield will gain Rage from taking damage despite the damage being absorbed, and Righteous Fury will trigger from damage absorbed by your Power Word: Shield as if it were a heal.", instructions: nil)
# Rune.create!(name: "Twisted Faith", character_class: "Priest", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_mindtwisting.jpg", description: "Mind Flay and Mind Blast deal 50% increased damage to targets afflicted with your Shadow Word: Pain.", instructions: nil)
# Rune.create!(name: "Void Plague", character_class: "Priest", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_deathknight_bloodplague.jpg", description: "Afflicts the target with a disease that causes 116 Shadow damage over 18 sec.", instructions: nil)

# Priest Legs Runes
# Rune.create!(name: "Homunculi", character_class: "Priest", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_twistedfaith.jpg", description: "Break off splinters of your soul to animate 3 miniature copies of yourself that attempt to attack your current target with a mace, sword, and axe, reducing the attack speed, attack power, and armor respectively of any target they hit.", instructions: nil)
# Rune.create!(name: "Power Word: Barrier", character_class: "Priest", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_powerwordbarrier.jpg", description: "Summons a holy barrier to protect all party members at the target location for 10 sec, reducing all damage taken by 25% and preventing damage from delaying spellcasting.", instructions: nil)
# Rune.create!(name: "Prayer of Mending", character_class: "Priest", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_prayerofmendingtga.jpg", description: "Places a spell on the target that heals them for 150 the next time they take damage or receive healing.  When the heal occurs, Prayer of Mending jumps to a party or raid member within 20 yards.  Jumps up to 5 times and lasts 30 sec after each jump.  This spell can only be placed on one target at a time.", instructions: nil)
# Rune.create!(name: "Shared Pain", character_class: "Priest", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_gathershadows.jpg", description: "Your Shadow Word: Pain now also afflicts up to 2 additional nearby targets within 15 yards.", instructions: nil)

# Rogue Gloves Runes
# Rune.create!(name: "Main Gauche", character_class: "Rogue", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_deathknight_spelldeflection.jpg", description: "Instantly strike with your off-hand weapon for normal off-hand weapon damage and increase your chance to parry by 10% for 10 sec.  Awards 1 combo point. Main Gauche benefits from all talents and effects that trigger from or modify Sinister Strike.", instructions: nil)
# Rune.create!(name: "Mutilate", character_class: "Rogue", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_rogue_shadowstrikes.jpg", description: "Instantly attacks with both weapons for 100% weapon damage plus an additional 20 with each weapon.  Damage is increased by 20% against Poisoned targets.  Awards 2 combo points. Mutilate benefits from all talents and effects that trigger from or modify Backstab unless otherwise specified.", instructions: nil)
# Rune.create!(name: "Saber Slash", character_class: "Rogue", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_1h_haremmatron_d_01.jpg", description: "Viciously slash an enemy for 100% weapon damage, and cause the target to bleed for 11 damage every 2 sec for 12 sec, stacking up to 3 times.  Awards 1 combo point. Saber Slash benefits from all talents and effects that trigger from or modify Sinister Strike.", instructions: nil)
# Rune.create!(name: "Shadowstrike", character_class: "Rogue", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_rogue_envelopingshadows.jpg", description: "Teleport behind your target and strike, causing 150% weapon damage to the target.  Must be stealthed.  Awards 1 combo point.", instructions: nil)
# Rune.create!(name: "Shiv", character_class: "Rogue", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/inv_throwingknife_04.jpg", description: "Instantly attack with your off-hand weapon to deal normal off-hand weapon damage with a 100% chance to apply the poison from your off-hand weapon to the target. Slower weapons require more energy. Awards 1 combo point. Shiv benefits from all talents and effects that trigger from or modify Sinister Strike.", instructions: nil)

# Rogue Chest Runes
# Rune.create!(name: "Deadly Brew", character_class: "Rogue", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_potion_97.jpg", description: "Grants several improvements to your poisons: When you inflict any other poison on a target, you also inflict Deadly Poison. If your weapon does not have a poison applied, it has a chance to trigger Instant Poison as if Instant Poison were applied. Deadly Poison and Instant Poison now gain increased damage from your Attack Power.", instructions: nil)
# Rune.create!(name: "Just a Flesh Wound", character_class: "Rogue", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_rogue_bloodyeye.jpg", description: "You take 20% reduced Physical damage while Blade Dance is active. Additionally, you have 6% reduced chance to be critically hit by melee attacks, the threat generated by all your actions is massively increased, and your Feint ability is replaced with Tease, which Taunts the target to attack you. Taunts the target to attack you, but has no effect if the target is already attacking you.", instructions: nil)
# Rune.create!(name: "Quick Draw", character_class: "Rogue", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_musket_02.jpg", description: "Draw your ranged weapon and fire a quick shot at an enemy, causing normal ranged weapon damage and reducing the target's movement speed by 50% for 6 sec. Awards 1 combo point. Quick Draw benefits from all talents and effects that trigger from or modify Sinister Strike.", instructions: nil)
# Rune.create!(name: "Slaughter from the Shadows", character_class: "Rogue", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_rogue_slaughterfromtheshadows.jpg", description: "Reduces the Energy cost of your Backstab and Ambush abilities by 20. Does not apply to abilities learned from other runes.", instructions: nil)

# Rogue Legs Runes
# Rune.create!(name: "Between the Eyes", character_class: "Rogue", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/inv_weapon_rifle_01.jpg", description: "Ranged Finishing move that causes damage per combo point, increased by Attack Power, and Stuns the target:

# 1 point: 27 to 41 damage, 1 sec Stun
# 2 points: 43 to 66 damage, 2 sec Stun
# 3 points: 59 to 91 damage, 3 sec Stun
# 4 points: 76 to 116 damage, 4 sec Stun
# 5 points: 92 to 144 damage, 5 sec Stun

# Cooldown shared with Kidney Shot.", instructions: nil)
# Rune.create!(name: "Blade Dance", character_class: "Rogue", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warrior_punishingblow.jpg", description: "Finishing move that increases your Parry chance by 10%.  Lasts longer per combo point:

# 1 point: 14 seconds
# 2 points: 18 seconds
# 3 points: 22 seconds
# 4 points: 26 seconds
# 5 points: 30 seconds", instructions: nil)
# Rune.create!(name: "Envenom", character_class: "Rogue", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/ability_rogue_disembowel.jpg", description: "Finishing move that deals instant poison damage based on your Deadly Poison doses on the target.  Following the Envenom attack you have a 75% increased frequency of applying Instant Poison for 1 sec plus an additional 1 sec per combo point. One dose is activated per combo point:

# 1 point: 40 Damage
# 2 points: 80 Damage
# 3 points: 120 Damage
# 4 points: 160 Damage
# 5 points: 200 Damage", instructions: nil)

# Paladin Gloves Runes
# Rune.create!(name: "Beacon of Light", character_class: "Paladin", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_paladin_beaconoflight.jpg", description: "The target becomes a Beacon of Light to all members of your party or raid within a 40 yard radius.  Any heals you cast on party or raid members will also heal the Beacon for 100% of the amount healed.  Only one target can be the Beacon of Light at a time. Lasts 1 min.", instructions: nil)
# Rune.create!(name: "Crusader Strike", character_class: "Paladin", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_crusaderstrike.jpg", description: "An instant strike that causes 75% weapon damage and regenerates 2% of your maximum mana.", instructions: nil)
# Rune.create!(name: "Hand of Reckoning", character_class: "Paladin", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_unyieldingfaith.jpg", description: "Taunts the target to attack you, but has no effect if the target is already attacking you. While you know this ability, the threat bonus from Righteous Fury is increased to 80% and Righteous Fury causes you to gain mana when healed by others equal to 25% of the amount healed. Additionally, while Righteous Fury is active, damage which takes you below 35% health is reduced by 20%. Righteous Fury will remain active until cancelled.", instructions: nil)

# Paladin Chest Runes
# Rune.create!(name: "Aegis", character_class: "Paladin", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_shield_48.jpg", description: "Increases your block value by 30% and damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 30%.  Lasts 10 sec or 5 blocks. Effect not cumulative with Redoubt.", instructions: nil)
# Rune.create!(name: "Divine Storm", character_class: "Paladin", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/ability_paladin_divinestorm.jpg", description: "An instant weapon attack that causes 110% of weapon damage to up to 4 enemies within 8 yards.  The Divine Storm heals up to 3 party or raid members totaling 25% of the damage caused.", instructions: nil)
# Rune.create!(name: "Horn of Lordaeron", character_class: "Paladin", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/inv_misc_horn_03.jpg", description: "The Paladin blows the Horn of Lordaeron, which increases total Strength and Agility of all party members within 30 yards by 6. Lasts 2 min. Exclusive with Blessing of Might.", instructions: nil)
# Rune.create!(name: "Seal of Martyrdom", character_class: "Paladin", rune_slot: "Chest", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_sealofblood.jpg", description: "Fills you with holy spirit for 30 sec, causing each of your melee attacks to deal 30% weapon damage to your target, but you lose health equal to 10% of the damage inflicted. While this seal is active, your party and raid members within 40 yards each gain mana equal to 20% of damage you take from this seal.

# Unleashing this Seal's energy will judge an enemy, instantly causing 70% weapon damage at the cost of health equal to 10% of the damage inflicted.", instructions: nil)

# Paladin Legs Runes
# Rune.create!(name: "Avenger's Shield", character_class: "Paladin", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_avengersshield.jpg", description: "Hurls a holy shield at the enemy, dealing 165 to 197 Holy damage, Dazing them and then jumping to additional nearby enemies.  Affects 3 total targets.  Lasts 10 sec.", instructions: nil)
# Rune.create!(name: "Divine Sacrifice", character_class: "Paladin", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_powerwordbarrier.jpg", description: "30% of all damage taken by party members within 30 yards is redirected to the Paladin for 10 sec. Damage which reduces the Paladin below 20% health will break the effect and grant the paladin 10% increased damage and healing done for 10 sec. Divine Sacrifice cannot be used while you are under the effects of Blessing of Protection, Divine Shield, or Divine Protection, and prevents you from being targeted by those abilities while it is active.", instructions: nil)
# Rune.create!(name: "Exorcist", character_class: "Paladin", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_retribution.jpg", description: "Exorcism can now be cast on any target and has 100% increased critical strike chance against Undead and Demons.", instructions: nil)
# Rune.create!(name: "Inspiration Exemplar", character_class: "Paladin", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/spell_holy_power.jpg", description: "Your inspiring presence periodically dispels Fear and Sleep effects on nearby party members.", instructions: nil)
# Rune.create!(name: "Rebuke", character_class: "Paladin", rune_slot: "Legs", image_url: "https://cdn.sixtyupgrades.com/icons/inv_relics_totemofrage.jpg", description: "Interrupts spellcasting and prevents any spell in that school from being cast for 2 sec.", instructions: nil)

# Warlock Gloves Runes
# Rune.create!(name: "Chaos Bolt", character_class: "Warlock", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warlock_chaosbolt.jpg", description: "Sends a bolt of chaotic fire at the enemy, dealing 225 to 286 Fire damage.  Chaos Bolt always hits, cannot be resisted, and its knowledge causes all your Fire spells to pierce through absorption effects. Chaos Bolt gains a high chance to be resisted when used against monsters 4 or more levels above your level.", instructions: nil)
# Rune.create!(name: "Haunt", character_class: "Warlock", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/ability_warlock_haunt.jpg", description: "Unleash a ghostly soul on an enemy, dealing 108 to 127 damage, and increasing all Shadow damage over time you deal to that target by 20%. When the Haunt ends or is dispelled, you will be healed for all the damage it dealt to your target.", instructions: nil)
# Rune.create!(name: "Metamorphosis", character_class: "Warlock", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_nature_wispsplode.jpg", description: "Transform into a Demon, increasing Armor by 500%, reducing the chance you will be critically hit by 6%, increasing your threat by 50%, increasing mana gained from Life Tap by 100%, transforming the functionality of some of your abilities, and granting some new abilities:

# Searing Pain: Now instant.

# Shadow Bolt: Becomes Shadow Cleave, a Shadow melee attack that hits up to 3 nearby enemies, but has a 6 sec cooldown.

# Fear: Replaced with Menace.
# Taunts the target to attack you, but has no effect if the target is already attacking you.

# Demon Charge
# Charge an enemy and stun it for 1 sec.  Cannot be used in combat.

# Demonic Howl
# Forces all nearby enemies to focus attacks on you for 6 sec.", instructions: nil)
# Rune.create!(name: "Shadow Bolt Volley", character_class: "Warlock", rune_slot: "Gloves", image_url: "https://cdn.sixtyupgrades.com/icons/spell_shadow_blackplague.jpg", description: "Your Shadow Bolt now strikes up to 5 targets within a chain distance of 10 yards, but for 20% reduced damage.", instructions: nil)
